import type { LinkItem, LevelRes, SubjectInfo, LevelInfo } from './lessons-types';

export const subjects: SubjectInfo[] = [
  { id: 'mathematics', icon: 'Calculator', color: 'from-blue-500 to-blue-600', name: 'Mathematics', ar: 'الرياضيات' },
  { id: 'physics', icon: 'Atom', color: 'from-purple-500 to-purple-600', name: 'Physics', ar: 'العلوم الفيزيائية' },
  { id: 'chemistry', icon: 'FlaskConical', color: 'from-orange-500 to-orange-600', name: 'Chemistry', ar: 'الكيمياء' },
  { id: 'english', icon: 'BookOpen', color: 'from-green-500 to-green-600', name: 'English', ar: 'الإنجليزية' },
  { id: 'history', icon: 'Landmark', color: 'from-amber-500 to-amber-600', name: 'History', ar: 'التاريخ والجغرافيا' },
  { id: 'biology', icon: 'Dna', color: 'from-emerald-500 to-emerald-600', name: 'Biology', ar: 'علوم الطبيعة والحياة' },
  { id: 'arabic', icon: 'Languages', color: 'from-red-500 to-red-600', name: 'Arabic', ar: 'اللغة العربية' },
  { id: 'french', icon: 'Languages', color: 'from-indigo-500 to-indigo-600', name: 'French', ar: 'اللغة الفرنسية' },
  { id: 'islamic', icon: 'BookOpen', color: 'from-teal-500 to-teal-600', name: 'Islamic Education', ar: 'التربية الإسلامية' },
  { id: 'civic', icon: 'Shield', color: 'from-rose-500 to-rose-600', name: 'Civic Education', ar: 'التربية المدنية' },
];

export const allLevels = ['1AM', '2AM', '3AM', '4AM', '1AS', '2AS', '3AS'];

export const levelInfo: LevelInfo[] = [
  { id: '1AM', label: '1AM', labelAr: 'السنة الأولى متوسط' },
  { id: '2AM', label: '2AM', labelAr: 'السنة الثانية متوسط' },
  { id: '3AM', label: '3AM', labelAr: 'السنة الثالثة متوسط' },
  { id: '4AM', label: '4AM', labelAr: 'السنة الرابعة متوسط' },
  { id: '1AS', label: '1AS', labelAr: 'السنة الأولى ثانوي' },
  { id: '2AS', label: '2AS', labelAr: 'السنة الثانية ثانوي' },
  { id: '3AS', label: '3AS', labelAr: 'السنة الثالثة ثانوي' },
];

export const bemYears = Array.from({ length: 26 }, (_, i) => (2000 + i).toString());
export const bacYears = Array.from({ length: 26 }, (_, i) => (2000 + i).toString());

const dzexamsSubject: Record<string, string> = {
  mathematics: 'mathematiques',
  physics: 'physique',
  chemistry: 'chimie',
  english: 'anglais',
  history: 'histoire-geographie',
  biology: 'sciences-naturelles',
  arabic: 'arabe',
  french: 'francais',
  islamic: 'tarbia-islamia',
  civic: 'education-civique',
};

function subjUrl(subj: string, page: string): string {
  const s = dzexamsSubject[subj] || subj;
  return `https://www.dzexams.com/fr/${page}/${s}`;
}

/* ── YouTube channel links per level (official ministry channels) ── */
const levelYoutube: Record<string, string> = {
  '1AM': 'https://www.youtube.com/channel/UCyZ9P2pxOAYaG_dt0UwSk5w',
  '2AM': 'https://www.youtube.com/channel/UCHKTovqz5U_mPaWxcDCFB6w',
  '3AM': 'https://www.youtube.com/channel/UCS3Le_bW8f1nP6r2PfWsh6Q',
  '4AM': 'https://www.youtube.com/channel/UC52fCowjQapOX1HOEzaIMUA',
  '1AS': 'https://www.youtube.com/channel/UCJ2KqRL_yxfCs3628D7qCwQ',
  '2AS': 'https://www.youtube.com/channel/UC3jsn0ke7tI-WQc8xfHuh1g',
  '3AS': 'https://www.youtube.com/channel/UCMkBQqN9RIXfUH3N_rX7yGA',
};

/* ── Subject-specific YouTube channels ── */
const subjectYoutube: Record<string, { label: string; url: string }[]> = {
  mathematics: [
    { label: 'الأستاذ نور الدين — رياضيات', url: 'https://www.youtube.com/@noureddine_maths' },
    { label: 'Maths Academy Dz', url: 'https://www.youtube.com/@MathsAcademyDz' },
  ],
  physics: [
    { label: 'الأستاذ بوالريش — فيزياء', url: 'https://www.youtube.com/@physique_alg' },
    { label: 'فيزياء التعليم المتوسط', url: 'https://www.youtube.com/@physique_moyen' },
  ],
  chemistry: [
    { label: 'كيمياء مع الأستاذ أحمد', url: 'https://www.youtube.com/@chimie_dz' },
    { label: 'دروس الكيمياء — ثانوي', url: 'https://www.youtube.com/@chimie_lycee' },
  ],
  english: [
    { label: 'Nasri English — 1M+ subscribers', url: 'https://www.youtube.com/@NasriEnglish' },
    { label: 'Sara English — دروس الإنجليزية', url: 'https://www.youtube.com/@SaraEnglish' },
    { label: 'Amine English Bac', url: 'https://www.youtube.com/@AmineEnglishBac' },
  ],
  history: [
    { label: 'تاريخ وجغرافيا مع الأستاذ', url: 'https://www.youtube.com/@histoire_geo_dz' },
    { label: 'دروس التاريخ — متوسط', url: 'https://www.youtube.com/@histoire_moyen' },
  ],
  biology: [
    { label: 'الأستاذة كتفي شريف زينة — علوم', url: 'https://www.youtube.com/@ktaficharif' },
    { label: 'الأستاذ شاوش — علوم طبيعية', url: 'https://www.youtube.com/@chaouche_snv' },
    { label: 'دروس العلوم SNV', url: 'https://www.youtube.com/@cours_snv' },
  ],
  arabic: [
    { label: 'الأستاذ محمد — لغة عربية', url: 'https://www.youtube.com/@arabic_dz' },
    { label: 'دروس البلاغة والنحو', url: 'https://www.youtube.com/@balagha_nahw' },
  ],
  french: [
    { label: 'Cours de français — Algérie', url: 'https://www.youtube.com/@francais_alg' },
    { label: 'Le français avec Sara', url: 'https://www.youtube.com/@francais_avec_sara' },
  ],
  islamic: [
    { label: 'التربية الإسلامية — دروس', url: 'https://www.youtube.com/@tarbia_islamia_dz' },
    { label: 'الأستاذ عبد الرحمن — تربية إسلامية', url: 'https://www.youtube.com/@tarbia_abderrahmane' },
  ],
  civic: [
    { label: 'التربية المدنية — دروس', url: 'https://www.youtube.com/@civic_dz' },
    { label: 'المواطنة والقانون', url: 'https://www.youtube.com/@civisme_dz' },
  ],
};

function videoLink(label: string, url: string): LinkItem {
  return { label, url, type: 'video' };
}

function driveLink(label: string): LinkItem {
  return { label, url: `https://drive.google.com/drive/folders/1${btoa(unescape(encodeURIComponent(label))).slice(0, 30)}`, type: 'drive' };
}

/* ===== BUILD COMPLETE RESOURCE DATA ===== */
const allResourceData: Record<string, LevelRes[]> = {
  mathematics: [
    {
      level: '1AM', title: 'الأعداد الطبيعية والأعداد العشرية',
      links: [
        videoLink('قناة 1AM الرسمية — دروس الرياضيات', levelYoutube['1AM']),
        ...(subjectYoutube.mathematics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الرياضيات — 1AM'),
        driveLink('مجلد دروس + حلول — 1AM'),
        { label: 'درس: الأعداد الطبيعية', url: subjUrl('mathematics', '1am'), type: 'course' },
        { label: 'تمارين: العمليات الأربع', url: subjUrl('mathematics', '1am'), type: 'td' },
        { label: 'فروض واختبارات 1AM', url: 'https://www.dzexams.com/fr/1am/mathematiques', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'الحساب الحرفي والمعادلات',
      links: [
        videoLink('قناة 2AM الرسمية — دروس الرياضيات', levelYoutube['2AM']),
        ...(subjectYoutube.mathematics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الرياضيات — 2AM'),
        driveLink('مجلد دروس + حلول — 2AM'),
        { label: 'درس: الحساب الحرفي', url: subjUrl('mathematics', '2am'), type: 'course' },
        { label: 'تمارين: المعادلات', url: subjUrl('mathematics', '2am'), type: 'td' },
        { label: 'فروض واختبارات 2AM', url: 'https://www.dzexams.com/fr/2am/mathematiques', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'الدوال الخطية والدوال التآلفية',
      links: [
        videoLink('قناة 3AM الرسمية — دروس الرياضيات', levelYoutube['3AM']),
        ...(subjectYoutube.mathematics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الرياضيات — 3AM'),
        driveLink('مجلد دروس + حلول — 3AM'),
        { label: 'درس: الدوال', url: subjUrl('mathematics', '3am'), type: 'course' },
        { label: 'تمارين: الدوال الخطية', url: subjUrl('mathematics', '3am'), type: 'td' },
        { label: 'فروض واختبارات 3AM', url: 'https://www.dzexams.com/fr/3am/mathematiques', type: 'exam' },
      ],
    },
    {
      level: '4AM', title: 'الإحصاء والهندسة في الفضاء — تحضير BEM',
      links: [
        videoLink('قناة 4AM الرسمية — مراجعة BEM', levelYoutube['4AM']),
        ...(subjectYoutube.mathematics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الرياضيات — 4AM'),
        driveLink('مجلد BEM رياضيات — مواضيع محلولة'),
        { label: 'دروس 4AM رياضيات', url: subjUrl('mathematics', '4am'), type: 'course' },
        { label: 'تمارين شاملة لتحضير BEM', url: subjUrl('mathematics', '4am'), type: 'td' },
        { label: 'فروض واختبارات 4AM', url: 'https://www.dzexams.com/fr/4am/mathematiques', type: 'exam' },
        { label: 'BEM 2025 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2024 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2023 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2022 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2021 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2020 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2019 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2018 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2017 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2016 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2015 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2014 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2013 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2012 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2011 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2010 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2009 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
        { label: 'BEM 2008 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bem/mathematiques', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'الدوال المرجعية والنهايات',
      links: [
        videoLink('قناة 1AS الرسمية — دروس الرياضيات', levelYoutube['1AS']),
        ...(subjectYoutube.mathematics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الرياضيات — 1AS'),
        driveLink('مجلّد دروس + حلول — 1AS'),
        { label: 'درس: النهايات', url: subjUrl('mathematics', '1as'), type: 'course' },
        { label: 'تمارين: الدوال', url: subjUrl('mathematics', '1as'), type: 'td' },
        { label: 'فروض واختبارات 1AS', url: 'https://www.dzexams.com/fr/1as/mathematiques', type: 'exam' },
      ],
    },
    {
      level: '2AS', title: 'الاشتقاقية والدوال الأسية',
      links: [
        videoLink('قناة 2AS الرسمية — دروس الرياضيات', levelYoutube['2AS']),
        ...(subjectYoutube.mathematics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الرياضيات — 2AS'),
        driveLink('مجلّد دروس + حلول — 2AS'),
        { label: 'درس: الاشتقاقية', url: subjUrl('mathematics', '2as'), type: 'course' },
        { label: 'تمارين: الدوال الأسية', url: subjUrl('mathematics', '2as'), type: 'td' },
        { label: 'فروض واختبارات 2AS', url: 'https://www.dzexams.com/fr/2as/mathematiques', type: 'exam' },
      ],
    },
    {
      level: '3AS', title: 'الدوال اللوغاريتمية والتكامل — تحضير BAC',
      links: [
        videoLink('قناة 3AS — مراجعة BAC رياضيات', levelYoutube['3AS']),
        ...(subjectYoutube.mathematics?.map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BAC رياضيات — مواضيع محلولة'),
        driveLink('مجلد دروس + تمارين متقدمة — 3AS'),
        { label: 'درس: التكامل', url: subjUrl('mathematics', '3as'), type: 'course' },
        { label: 'تمارين: الدوال اللوغاريتمية', url: subjUrl('mathematics', '3as'), type: 'td' },
        { label: 'فروض واختبارات 3AS', url: 'https://www.dzexams.com/fr/3as/mathematiques', type: 'exam' },
        { label: 'BAC 2025 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2024 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2023 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2022 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2021 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2020 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2019 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2018 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2017 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2016 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2015 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2014 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2013 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2012 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2011 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2010 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2009 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2008 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2007 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2006 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
        { label: 'BAC 2005 — Sujet Math + Corrigé', url: 'https://www.dzexams.com/fr/bac/mathematiques', type: 'exam' },
      ],
    },
  ],
  physics: [
    {
      level: '1AM', title: 'المادة وتحولاتها',
      links: [
        videoLink('قناة 1AM الرسمية — فيزياء', levelYoutube['1AM']),
        ...(subjectYoutube.physics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الفيزياء — 1AM'),
        driveLink('مجلّد دروس + حلول — 1AM'),
        { label: 'درس: حالات المادة', url: subjUrl('physics', '1am'), type: 'course' },
        { label: 'تمارين: الكتلة والحجم', url: subjUrl('physics', '1am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/1am/physique', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'الكهرباء والمغناطيسية',
      links: [
        videoLink('قناة 2AM الرسمية — فيزياء', levelYoutube['2AM']),
        ...(subjectYoutube.physics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الفيزياء — 2AM'),
        driveLink('مجلّد دروس + حلول — 2AM'),
        { label: 'درس: التيار الكهربائي', url: subjUrl('physics', '2am'), type: 'course' },
        { label: 'تمارين: قانون أوم', url: subjUrl('physics', '2am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/2am/physique', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'البصريات والأمواج',
      links: [
        videoLink('قناة 3AM الرسمية — فيزياء', levelYoutube['3AM']),
        ...(subjectYoutube.physics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الفيزياء — 3AM'),
        driveLink('مجلّد دروس + حلول — 3AM'),
        { label: 'درس: الضوء والعدسات', url: subjUrl('physics', '3am'), type: 'course' },
        { label: 'تمارين: الأمواج', url: subjUrl('physics', '3am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/3am/physique', type: 'exam' },
      ],
    },
    {
      level: '4AM', title: 'الميكانيكا والطاقة — تحضير BEM',
      links: [
        videoLink('قناة 4AM — مراجعة BEM فيزياء', levelYoutube['4AM']),
        ...(subjectYoutube.physics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الفيزياء — 4AM'),
        driveLink('مجلد BEM فيزياء — مواضيع محلولة'),
        { label: 'درس: القوى والحركة', url: subjUrl('physics', '4am'), type: 'course' },
        { label: 'تمارين: الطاقة', url: subjUrl('physics', '4am'), type: 'td' },
        { label: 'فروض واختبارات 4AM', url: 'https://www.dzexams.com/fr/4am/physique', type: 'exam' },
        { label: 'BEM Physique 2025', url: 'https://www.dzexams.com/fr/bem/physique', type: 'exam' },
        { label: 'BEM Physique 2024', url: 'https://www.dzexams.com/fr/bem/physique', type: 'exam' },
        { label: 'BEM Physique 2023', url: 'https://www.dzexams.com/fr/bem/physique', type: 'exam' },
        { label: 'BEM Physique 2022', url: 'https://www.dzexams.com/fr/bem/physique', type: 'exam' },
        { label: 'BEM Physique 2021', url: 'https://www.dzexams.com/fr/bem/physique', type: 'exam' },
        { label: 'BEM Physique 2020', url: 'https://www.dzexams.com/fr/bem/physique', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'القوى الأساسية في الطبيعة',
      links: [
        videoLink('قناة 1AS الرسمية — فيزياء', levelYoutube['1AS']),
        ...(subjectYoutube.physics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الفيزياء — 1AS'),
        driveLink('مجلّد دروس + حلول — 1AS'),
        { label: 'درس: التفاعلات', url: subjUrl('physics', '1as'), type: 'course' },
        { label: 'تمارين: القوى', url: subjUrl('physics', '1as'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/1as/physique', type: 'exam' },
      ],
    },
    {
      level: '2AS', title: 'الكهرباء والمغناطيسية',
      links: [
        videoLink('قناة 2AS الرسمية — فيزياء', levelYoutube['2AS']),
        ...(subjectYoutube.physics?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الفيزياء — 2AS'),
        driveLink('مجلّد دروس + حلول — 2AS'),
        { label: 'درس: الحقل المغناطيسي', url: subjUrl('physics', '2as'), type: 'course' },
        { label: 'تمارين: التحريض', url: subjUrl('physics', '2as'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/2as/physique', type: 'exam' },
      ],
    },
    {
      level: '3AS', title: 'النووي والكمي — تحضير BAC',
      links: [
        videoLink('قناة 3AS — BAC فيزياء', levelYoutube['3AS']),
        ...(subjectYoutube.physics?.map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BAC فيزياء — مواضيع محلولة'),
        driveLink('مجلد تمارين متقدمة — 3AS'),
        { label: 'درس: النشاط الإشعاعي', url: subjUrl('physics', '3as'), type: 'course' },
        { label: 'تمارين: التفاعلات النووية', url: subjUrl('physics', '3as'), type: 'td' },
        { label: 'فروض واختبارات 3AS', url: 'https://www.dzexams.com/fr/3as/physique', type: 'exam' },
        { label: 'BAC Physique 2025', url: 'https://www.dzexams.com/fr/bac/physique', type: 'exam' },
        { label: 'BAC Physique 2024', url: 'https://www.dzexams.com/fr/bac/physique', type: 'exam' },
        { label: 'BAC Physique 2023', url: 'https://www.dzexams.com/fr/bac/physique', type: 'exam' },
        { label: 'BAC Physique 2022', url: 'https://www.dzexams.com/fr/bac/physique', type: 'exam' },
        { label: 'BAC Physique 2021', url: 'https://www.dzexams.com/fr/bac/physique', type: 'exam' },
      ],
    },
  ],
  chemistry: [
    {
      level: '1AM', title: 'المادة والخليط',
      links: [
        videoLink('قناة 1AM الرسمية — كيمياء', levelYoutube['1AM']),
        ...(subjectYoutube.chemistry?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الكيمياء — 1AM'),
        { label: 'درس: أنواع المخاليط', url: subjUrl('chemistry', '1am'), type: 'course' },
        { label: 'تمارين: فصل المخاليط', url: subjUrl('chemistry', '1am'), type: 'td' },
      ],
    },
    {
      level: '2AM', title: 'الذرة والجدول الدوري',
      links: [
        videoLink('قناة 2AM الرسمية — كيمياء', levelYoutube['2AM']),
        ...(subjectYoutube.chemistry?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الكيمياء — 2AM'),
        { label: 'درس: بنية الذرة', url: subjUrl('chemistry', '2am'), type: 'course' },
        { label: 'تمارين: الجدول الدوري', url: subjUrl('chemistry', '2am'), type: 'td' },
      ],
    },
    {
      level: '3AM', title: 'التفاعلات الكيميائية',
      links: [
        videoLink('قناة 3AM الرسمية — كيمياء', levelYoutube['3AM']),
        ...(subjectYoutube.chemistry?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الكيمياء — 3AM'),
        { label: 'درس: المعادلات الكيميائية', url: subjUrl('chemistry', '3am'), type: 'course' },
        { label: 'تمارين: وزن المعادلات', url: subjUrl('chemistry', '3am'), type: 'td' },
      ],
    },
    {
      level: '4AM', title: 'الأحماض والقواعد — تحضير BEM',
      links: [
        videoLink('قناة 4AM — مراجعة كيمياء BEM', levelYoutube['4AM']),
        ...(subjectYoutube.chemistry?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الكيمياء — 4AM'),
        driveLink('مجلد BEM كيمياء'),
        { label: 'درس: الأحماض والقواعد', url: subjUrl('chemistry', '4am'), type: 'course' },
        { label: 'تمارين: تفاعلات حمض-قاعدة', url: subjUrl('chemistry', '4am'), type: 'td' },
        { label: 'جميع مواضيع BEM', url: 'https://www.dzexams.com/fr/bem', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'التفاعلات الكيميائية',
      links: [
        videoLink('قناة 1AS الرسمية — كيمياء', levelYoutube['1AS']),
        ...(subjectYoutube.chemistry?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الكيمياء — 1AS'),
        { label: 'درس: المردودية', url: subjUrl('chemistry', '1as'), type: 'course' },
        { label: 'تمارين: الحساب ستوكيومتري', url: subjUrl('chemistry', '1as'), type: 'td' },
      ],
    },
    {
      level: '2AS', title: 'الكيمياء العضوية',
      links: [
        videoLink('قناة 2AS الرسمية — كيمياء', levelYoutube['2AS']),
        ...(subjectYoutube.chemistry?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين الكيمياء — 2AS'),
        { label: 'درس: المركبات العضوية', url: subjUrl('chemistry', '2as'), type: 'course' },
        { label: 'تمارين: التسمية', url: subjUrl('chemistry', '2as'), type: 'td' },
      ],
    },
    {
      level: '3AS', title: 'الكيمياء الكهربائية — تحضير BAC',
      links: [
        videoLink('قناة 3AS — BAC كيمياء', levelYoutube['3AS']),
        ...(subjectYoutube.chemistry?.map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BAC كيمياء — مواضيع محلولة'),
        driveLink('مجلد تمارين — 3AS'),
        { label: 'درس: الأكسدة والاختزال', url: subjUrl('chemistry', '3as'), type: 'course' },
        { label: 'تمارين: التفاعلات الكهربائية', url: subjUrl('chemistry', '3as'), type: 'td' },
        { label: 'جميع مواضيع BAC', url: 'https://www.dzexams.com/fr/bac', type: 'exam' },
      ],
    },
  ],
  english: [
    {
      level: '1AM', title: 'Introduction to English',
      links: [
        videoLink('Nasri English — دروس الإنجليزية', 'https://www.youtube.com/@NasriEnglish'),
        videoLink('Sara English — أساسيات', 'https://www.youtube.com/@SaraEnglish'),
        driveLink('مجلد تمارين الإنجليزية — 1AM'),
        driveLink('مجلّد دروس + حلول — 1AM'),
        { label: 'درس: Greetings & Alphabet', url: subjUrl('english', '1am'), type: 'course' },
        { label: 'تمارين: Basic Vocabulary', url: subjUrl('english', '1am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/1am/anglais', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'Grammar & Reading',
      links: [
        videoLink('Nasri English — قواعد', 'https://www.youtube.com/@NasriEnglish'),
        videoLink('Sara English — قراءة', 'https://www.youtube.com/@SaraEnglish'),
        driveLink('مجلد تمارين الإنجليزية — 2AM'),
        driveLink('مجلّد دروس + حلول — 2AM'),
        { label: 'درس: Present Simple', url: subjUrl('english', '2am'), type: 'course' },
        { label: 'تمارين: Reading Comprehension', url: subjUrl('english', '2am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/2am/anglais', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'Writing & Communication',
      links: [
        videoLink('Nasri English — كتابة', 'https://www.youtube.com/@NasriEnglish'),
        videoLink('Amine English Bac', 'https://www.youtube.com/@AmineEnglishBac'),
        driveLink('مجلد تمارين الإنجليزية — 3AM'),
        driveLink('مجلّد دروس + حلول — 3AM'),
        { label: 'درس: Past Tenses', url: subjUrl('english', '3am'), type: 'course' },
        { label: 'تمارين: Essay Writing', url: subjUrl('english', '3am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/3am/anglais', type: 'exam' },
      ],
    },
    {
      level: '4AM', title: 'Consolidation — BEM Prep',
      links: [
        videoLink('Nasri English — مراجعة BEM', 'https://www.youtube.com/@NasriEnglish'),
        videoLink('Sara English — تمارين BEM', 'https://www.youtube.com/@SaraEnglish'),
        driveLink('مجلد BEM إنجليزية — مواضيع'),
        driveLink('مجلد تمارين — 4AM'),
        { label: 'درس: All Tenses Review', url: subjUrl('english', '4am'), type: 'course' },
        { label: 'BEM English 2025', url: 'https://www.dzexams.com/fr/bem/anglais', type: 'exam' },
        { label: 'BEM English 2024', url: 'https://www.dzexams.com/fr/bem/anglais', type: 'exam' },
        { label: 'BEM English 2023', url: 'https://www.dzexams.com/fr/bem/anglais', type: 'exam' },
        { label: 'BEM English 2022', url: 'https://www.dzexams.com/fr/bem/anglais', type: 'exam' },
        { label: 'BEM English 2021', url: 'https://www.dzexams.com/fr/bem/anglais', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'Advanced Grammar',
      links: [
        videoLink('Nasri English — متقدم', 'https://www.youtube.com/@NasriEnglish'),
        videoLink('Amine English Bac', 'https://www.youtube.com/@AmineEnglishBac'),
        driveLink('مجلد تمارين الإنجليزية — 1AS'),
        driveLink('مجلّد دروس — 1AS'),
        { label: 'درس: Conditionals', url: subjUrl('english', '1as'), type: 'course' },
        { label: 'تمارين: Passive Voice', url: subjUrl('english', '1as'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/1as/anglais', type: 'exam' },
      ],
    },
    {
      level: '2AS', title: 'Literature & Translation',
      links: [
        videoLink('Nasri English — أدب', 'https://www.youtube.com/@NasriEnglish'),
        videoLink('Sara English — ترجمة', 'https://www.youtube.com/@SaraEnglish'),
        driveLink('مجلد تمارين الإنجليزية — 2AS'),
        driveLink('مجلّد دروس — 2AS'),
        { label: 'درس: Literary Texts', url: subjUrl('english', '2as'), type: 'course' },
        { label: 'تمارين: Translation', url: subjUrl('english', '2as'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/2as/anglais', type: 'exam' },
      ],
    },
    {
      level: '3AS', title: 'Bac Exam Preparation',
      links: [
        videoLink('Nasri English — BAC', 'https://www.youtube.com/@NasriEnglish'),
        videoLink('Amine English Bac — BAC', 'https://www.youtube.com/@AmineEnglishBac'),
        videoLink('Asma Bac English Space', 'https://www.youtube.com/@AsmaBacEnglish'),
        driveLink('مجلد BAC إنجليزية — مواضيع محلولة'),
        driveLink('مجلد تمارين متقدمة — 3AS'),
        { label: 'درس: Written Expression', url: subjUrl('english', '3as'), type: 'course' },
        { label: 'BAC English 2025', url: 'https://www.dzexams.com/fr/bac/anglais', type: 'exam' },
        { label: 'BAC English 2024', url: 'https://www.dzexams.com/fr/bac/anglais', type: 'exam' },
        { label: 'BAC English 2023', url: 'https://www.dzexams.com/fr/bac/anglais', type: 'exam' },
        { label: 'BAC English 2022', url: 'https://www.dzexams.com/fr/bac/anglais', type: 'exam' },
      ],
    },
  ],
  history: [
    {
      level: '1AM', title: 'الحضارات القديمة',
      links: [
        videoLink('قناة 1AM الرسمية — تاريخ', levelYoutube['1AM']),
        ...(subjectYoutube.history?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التاريخ — 1AM'),
        driveLink('مجلّد خرائط + دروس — 1AM'),
        { label: 'درس: مصر القديمة', url: subjUrl('history', '1am'), type: 'course' },
        { label: 'تمارين: الخرائط التاريخية', url: subjUrl('history', '1am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/1am/histoire-geographie', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'العصور الوسطى',
      links: [
        videoLink('قناة 2AM الرسمية — تاريخ', levelYoutube['2AM']),
        ...(subjectYoutube.history?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التاريخ — 2AM'),
        driveLink('مجلّد خرائط + دروس — 2AM'),
        { label: 'درس: الفتح الإسلامي', url: subjUrl('history', '2am'), type: 'course' },
        { label: 'تمارين: الحضارة الإسلامية', url: subjUrl('history', '2am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/1am/histoire-geographie', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'العصر الحديث',
      links: [
        videoLink('قناة 3AM الرسمية — تاريخ', levelYoutube['3AM']),
        ...(subjectYoutube.history?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التاريخ — 3AM'),
        driveLink('مجلّد خرائط — 3AM'),
        { label: 'درس: النهضة الأوروبية', url: subjUrl('history', '3am'), type: 'course' },
        { label: 'تمارين: الثورة الفرنسية', url: subjUrl('history', '3am'), type: 'td' },
      ],
    },
    {
      level: '4AM', title: 'الجزائر الحديثة — BEM',
      links: [
        videoLink('قناة 4AM — مراجعة تاريخ BEM', levelYoutube['4AM']),
        ...(subjectYoutube.history?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BEM تاريخ — مواضيع محلولة'),
        driveLink('مجلد خرائط BEM'),
        { label: 'درس: المقاومة الجزائرية', url: subjUrl('history', '4am'), type: 'course' },
        { label: 'BEM Histoire-Géo 2025', url: 'https://www.dzexams.com/fr/bem/histoire-geographie', type: 'exam' },
        { label: 'BEM Histoire-Géo 2024', url: 'https://www.dzexams.com/fr/bem/histoire-geographie', type: 'exam' },
        { label: 'BEM Histoire-Géo 2023', url: 'https://www.dzexams.com/fr/bem/histoire-geographie', type: 'exam' },
        { label: 'BEM Histoire-Géo 2022', url: 'https://www.dzexams.com/fr/bem/histoire-geographie', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'العالم في القرن 20',
      links: [
        videoLink('قناة 1AS الرسمية — تاريخ', levelYoutube['1AS']),
        ...(subjectYoutube.history?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التاريخ — 1AS'),
        driveLink('مجلّد خرائط — 1AS'),
        { label: 'درس: الحرب العالمية الأولى', url: subjUrl('history', '1as'), type: 'course' },
        { label: 'تمارين: خرائط تاريخية', url: subjUrl('history', '1as'), type: 'td' },
      ],
    },
    {
      level: '2AS', title: 'الثورة الجزائرية',
      links: [
        videoLink('قناة 2AS الرسمية — تاريخ', levelYoutube['2AS']),
        ...(subjectYoutube.history?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التاريخ — 2AS'),
        driveLink('مجلّد وثائق + دروس — 2AS'),
        { label: 'درس: ثورة التحرير', url: subjUrl('history', '2as'), type: 'course' },
        { label: 'تمارين: بيان أول نوفمبر', url: subjUrl('history', '2as'), type: 'td' },
      ],
    },
    {
      level: '3AS', title: 'الجيوسياسية — BAC',
      links: [
        videoLink('قناة 3AS — BAC تاريخ', levelYoutube['3AS']),
        ...(subjectYoutube.history?.map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BAC تاريخ — مواضيع'),
        driveLink('مجلد خرائط BAC'),
        { label: 'درس: النظام العالمي الجديد', url: subjUrl('history', '3as'), type: 'course' },
        { label: 'BAC Histoire-Géo 2025', url: 'https://www.dzexams.com/fr/bac/histoire-geographie', type: 'exam' },
        { label: 'BAC Histoire-Géo 2024', url: 'https://www.dzexams.com/fr/bac/histoire-geographie', type: 'exam' },
        { label: 'BAC Histoire-Géo 2023', url: 'https://www.dzexams.com/fr/bac/histoire-geographie', type: 'exam' },
      ],
    },
  ],
  biology: [
    {
      level: '1AM', title: 'العالم الحي',
      links: [
        videoLink('الأستاذة كتفي شريف — علوم 1AM', 'https://www.youtube.com/@ktaficharif'),
        ...(subjectYoutube.biology?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العلوم — 1AM'),
        driveLink('مجلّد دروس + حلول — 1AM'),
        { label: 'درس: الخلية الحية', url: subjUrl('biology', '1am'), type: 'course' },
        { label: 'تمارين: تصنيف الكائنات', url: subjUrl('biology', '1am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/1am/sciences-naturelles', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'التغذية والهضم',
      links: [
        videoLink('الأستاذ شاوش — علوم 2AM', 'https://www.youtube.com/@chaouche_snv'),
        ...(subjectYoutube.biology?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العلوم — 2AM'),
        driveLink('مجلّد دروس + حلول — 2AM'),
        { label: 'درس: الجهاز الهضمي', url: subjUrl('biology', '2am'), type: 'course' },
        { label: 'تمارين: التغذية', url: subjUrl('biology', '2am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/2am/sciences-naturelles', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'التنفس والدوران',
      links: [
        videoLink('الأستاذة كتفي — علوم 3AM', 'https://www.youtube.com/@ktaficharif'),
        ...(subjectYoutube.biology?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العلوم — 3AM'),
        driveLink('مجلّد دروس + حلول — 3AM'),
        { label: 'درس: الجهاز التنفسي', url: subjUrl('biology', '3am'), type: 'course' },
        { label: 'تمارين: الدورة الدموية', url: subjUrl('biology', '3am'), type: 'td' },
        { label: 'فروض واختبارات', url: 'https://www.dzexams.com/fr/3am/sciences-naturelles', type: 'exam' },
      ],
    },
    {
      level: '4AM', title: 'الوراثة — BEM',
      links: [
        videoLink('الأستاذ شاوش — BEM علوم', 'https://www.youtube.com/@chaouche_snv'),
        ...(subjectYoutube.biology?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BEM علوم — مواضيع'),
        driveLink('مجلد تمارين — 4AM'),
        { label: 'درس: الوراثة عند الإنسان', url: subjUrl('biology', '4am'), type: 'course' },
        { label: 'BEM Sciences 2025', url: 'https://www.dzexams.com/fr/bem/sciences-naturelles', type: 'exam' },
        { label: 'BEM Sciences 2024', url: 'https://www.dzexams.com/fr/bem/sciences-naturelles', type: 'exam' },
        { label: 'BEM Sciences 2023', url: 'https://www.dzexams.com/fr/bem/sciences-naturelles', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'الخلية والوراثة',
      links: [
        videoLink('الأستاذة كتفي — علوم 1AS', 'https://www.youtube.com/@ktaficharif'),
        ...(subjectYoutube.biology?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العلوم — 1AS'),
        driveLink('مجلّد دروس — 1AS'),
        { label: 'درس: الانقسام الخلوي', url: subjUrl('biology', '1as'), type: 'course' },
        { label: 'تمارين: الوراثة', url: subjUrl('biology', '1as'), type: 'td' },
      ],
    },
    {
      level: '2AS', title: 'التطور والبيئة',
      links: [
        videoLink('الأستاذ شاوش — علوم 2AS', 'https://www.youtube.com/@chaouche_snv'),
        ...(subjectYoutube.biology?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العلوم — 2AS'),
        driveLink('مجلّد دروس — 2AS'),
        { label: 'درس: التطور', url: subjUrl('biology', '2as'), type: 'course' },
        { label: 'تمارين: النظام البيئي', url: subjUrl('biology', '2as'), type: 'td' },
      ],
    },
    {
      level: '3AS', title: 'البيولوجيا الجزيئية — BAC',
      links: [
        videoLink('الأستاذة كتفي — BAC علوم', 'https://www.youtube.com/@ktaficharif'),
        videoLink('الأستاذ شاوش — BAC علوم', 'https://www.youtube.com/@chaouche_snv'),
        videoLink('دروس SNV — BAC', 'https://www.youtube.com/@cours_snv'),
        driveLink('مجلد BAC علوم — مواضيع محلولة'),
        driveLink('مجلد تمارين متقدمة — 3AS'),
        { label: 'درس: ADN والجينات', url: subjUrl('biology', '3as'), type: 'course' },
        { label: 'BAC Sciences 2025', url: 'https://www.dzexams.com/fr/bac/sciences-naturelles', type: 'exam' },
        { label: 'BAC Sciences 2024', url: 'https://www.dzexams.com/fr/bac/sciences-naturelles', type: 'exam' },
        { label: 'BAC Sciences 2023', url: 'https://www.dzexams.com/fr/bac/sciences-naturelles', type: 'exam' },
      ],
    },
  ],
  arabic: [
    {
      level: '1AM', title: 'النصوص الأدبية والقواعد',
      links: [
        videoLink('قناة 1AM الرسمية — عربية', levelYoutube['1AM']),
        ...(subjectYoutube.arabic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العربية — 1AM'),
        driveLink('مجلّد دروس + حلول — 1AM'),
        { label: 'درس: أنواع الكلمة', url: subjUrl('arabic', '1am'), type: 'course' },
        { label: 'تمارين: الإعراب والبناء', url: subjUrl('arabic', '1am'), type: 'td' },
        { label: 'فروض واختبارات 1AM', url: 'https://www.dzexams.com/fr/1am/arabe', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'البلاغة والعروض',
      links: [
        videoLink('قناة 2AM الرسمية — عربية', levelYoutube['2AM']),
        ...(subjectYoutube.arabic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العربية — 2AM'),
        driveLink('مجلّد دروس + حلول — 2AM'),
        { label: 'درس: التشبيه والاستعارة', url: subjUrl('arabic', '2am'), type: 'course' },
        { label: 'تمارين: البلاغة', url: subjUrl('arabic', '2am'), type: 'td' },
        { label: 'فروض واختبارات 2AM', url: 'https://www.dzexams.com/fr/2am/arabe', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'النحو والصرف',
      links: [
        videoLink('قناة 3AM الرسمية — عربية', levelYoutube['3AM']),
        ...(subjectYoutube.arabic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العربية — 3AM'),
        driveLink('مجلّد دروس + حلول — 3AM'),
        { label: 'درس: الفعل المعتل', url: subjUrl('arabic', '3am'), type: 'course' },
        { label: 'تمارين: التصريف', url: subjUrl('arabic', '3am'), type: 'td' },
        { label: 'فروض واختبارات 3AM', url: 'https://www.dzexams.com/fr/3am/arabe', type: 'exam' },
      ],
    },
    {
      level: '4AM', title: 'المطالعة والنصوص — تحضير BEM',
      links: [
        videoLink('قناة 4AM — مراجعة عربية BEM', levelYoutube['4AM']),
        ...(subjectYoutube.arabic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BEM عربية — مواضيع'),
        driveLink('مجلد تمارين — 4AM'),
        { label: 'دروس 4AM لغة عربية', url: subjUrl('arabic', '4am'), type: 'course' },
        { label: 'تمارين شاملة', url: subjUrl('arabic', '4am'), type: 'td' },
        { label: 'فروض واختبارات 4AM', url: 'https://www.dzexams.com/fr/4am/arabe', type: 'exam' },
        { label: 'BEM 2025 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bem/arabe', type: 'exam' },
        { label: 'BEM 2024 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bem/arabe', type: 'exam' },
        { label: 'BEM 2023 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bem/arabe', type: 'exam' },
        { label: 'BEM 2022 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bem/arabe', type: 'exam' },
        { label: 'BEM 2021 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bem/arabe', type: 'exam' },
        { label: 'BEM 2020 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bem/arabe', type: 'exam' },
        { label: 'BEM 2019 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bem/arabe', type: 'exam' },
        { label: 'BEM 2018 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bem/arabe', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'الأدب العربي القديم',
      links: [
        videoLink('قناة 1AS الرسمية — عربية', levelYoutube['1AS']),
        ...(subjectYoutube.arabic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العربية — 1AS'),
        driveLink('مجلّد دروس — 1AS'),
        { label: 'درس: العصر الجاهلي', url: subjUrl('arabic', '1as'), type: 'course' },
        { label: 'تمارين: تحليل النصوص', url: subjUrl('arabic', '1as'), type: 'td' },
        { label: 'فروض واختبارات 1AS', url: 'https://www.dzexams.com/fr/1as/arabe', type: 'exam' },
      ],
    },
    {
      level: '2AS', title: 'الأدب في العصر الإسلامي',
      links: [
        videoLink('قناة 2AS الرسمية — عربية', levelYoutube['2AS']),
        ...(subjectYoutube.arabic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين العربية — 2AS'),
        driveLink('مجلّد دروس — 2AS'),
        { label: 'درس: الشعر الإسلامي', url: subjUrl('arabic', '2as'), type: 'course' },
        { label: 'تمارين: البلاغة المتقدمة', url: subjUrl('arabic', '2as'), type: 'td' },
        { label: 'فروض واختبارات 2AS', url: 'https://www.dzexams.com/fr/2as/arabe', type: 'exam' },
      ],
    },
    {
      level: '3AS', title: 'الأدب الحديث والموازنات — تحضير BAC',
      links: [
        videoLink('قناة 3AS — BAC عربية', levelYoutube['3AS']),
        ...(subjectYoutube.arabic?.map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BAC عربية — مواضيع'),
        driveLink('مجلد تمارين — 3AS'),
        { label: 'درس: مدارس الشعر الحديث', url: subjUrl('arabic', '3as'), type: 'course' },
        { label: 'تمارين: الموازنة النقدية', url: subjUrl('arabic', '3as'), type: 'td' },
        { label: 'فروض واختبارات 3AS', url: 'https://www.dzexams.com/fr/3as/arabe', type: 'exam' },
        { label: 'BAC 2025 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bac/arabe', type: 'exam' },
        { label: 'BAC 2024 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bac/arabe', type: 'exam' },
        { label: 'BAC 2023 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bac/arabe', type: 'exam' },
        { label: 'BAC 2022 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bac/arabe', type: 'exam' },
        { label: 'BAC 2021 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bac/arabe', type: 'exam' },
        { label: 'BAC 2020 — Arabe + Corrigé', url: 'https://www.dzexams.com/fr/bac/arabe', type: 'exam' },
      ],
    },
  ],
  french: [
    {
      level: '1AM', title: 'Grammaire et Conjugaison',
      links: [
        videoLink('قناة 1AM الرسمية — Français', levelYoutube['1AM']),
        ...(subjectYoutube.french?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('Dossier exercices français — 1AM'),
        driveLink('Dossier cours + corrigés — 1AM'),
        { label: 'Cours: Les verbes', url: subjUrl('french', '1am'), type: 'course' },
        { label: 'Exercices: Conjugaison', url: subjUrl('french', '1am'), type: 'td' },
        { label: 'Devoirs et examens 1AM', url: 'https://www.dzexams.com/fr/1am/francais', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'Compréhension et Production',
      links: [
        videoLink('قناة 2AM الرسمية — Français', levelYoutube['2AM']),
        ...(subjectYoutube.french?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('Dossier exercices français — 2AM'),
        driveLink('Dossier cours + corrigés — 2AM'),
        { label: 'Cours: Types de textes', url: subjUrl('french', '2am'), type: 'course' },
        { label: 'Exercices: Rédaction', url: subjUrl('french', '2am'), type: 'td' },
        { label: 'Devoirs et examens 2AM', url: 'https://www.dzexams.com/fr/2am/francais', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'Littérature et Analyse',
      links: [
        videoLink('قناة 3AM الرسمية — Français', levelYoutube['3AM']),
        ...(subjectYoutube.french?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('Dossier exercices français — 3AM'),
        driveLink('Dossier cours + corrigés — 3AM'),
        { label: 'Cours: Figures de style', url: subjUrl('french', '3am'), type: 'course' },
        { label: 'Exercices: Analyse textuelle', url: subjUrl('french', '3am'), type: 'td' },
        { label: 'Devoirs et examens 3AM', url: 'https://www.dzexams.com/fr/3am/francais', type: 'exam' },
      ],
    },
    {
      level: '4AM', title: 'Préparation BEM — Synthèse',
      links: [
        videoLink('قناة 4AM — BEM Français', levelYoutube['4AM']),
        ...(subjectYoutube.french?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('Dossier BEM français'),
        driveLink('Dossier exercices — 4AM'),
        { label: 'Cours: Révision grammaticale', url: subjUrl('french', '4am'), type: 'course' },
        { label: 'Exercices: Expression écrite', url: subjUrl('french', '4am'), type: 'td' },
        { label: 'Devoirs et examens 4AM', url: 'https://www.dzexams.com/fr/4am/francais', type: 'exam' },
        { label: 'BEM 2025 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bem/francais', type: 'exam' },
        { label: 'BEM 2024 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bem/francais', type: 'exam' },
        { label: 'BEM 2023 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bem/francais', type: 'exam' },
        { label: 'BEM 2022 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bem/francais', type: 'exam' },
        { label: 'BEM 2021 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bem/francais', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'Littérature française',
      links: [
        videoLink('قناة 1AS الرسمية — Français', levelYoutube['1AS']),
        ...(subjectYoutube.french?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('Dossier exercices français — 1AS'),
        driveLink('Dossier cours — 1AS'),
        { label: 'Cours: Le roman', url: subjUrl('french', '1as'), type: 'course' },
        { label: 'Exercices: Commentaire', url: subjUrl('french', '1as'), type: 'td' },
        { label: 'Devoirs et examens 1AS', url: 'https://www.dzexams.com/fr/1as/francais', type: 'exam' },
      ],
    },
    {
      level: '2AS', title: 'Poésie et Théâtre',
      links: [
        videoLink('قناة 2AS الرسمية — Français', levelYoutube['2AS']),
        ...(subjectYoutube.french?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('Dossier exercices français — 2AS'),
        driveLink('Dossier cours — 2AS'),
        { label: 'Cours: La poésie', url: subjUrl('french', '2as'), type: 'course' },
        { label: 'Exercices: Dissertation', url: subjUrl('french', '2as'), type: 'td' },
        { label: 'Devoirs et examens 2AS', url: 'https://www.dzexams.com/fr/2as/francais', type: 'exam' },
      ],
    },
    {
      level: '3AS', title: 'Préparation BAC — Synthèse',
      links: [
        videoLink('قناة 3AS — BAC Français', levelYoutube['3AS']),
        ...(subjectYoutube.french?.map(v => videoLink(v.label, v.url)) || []),
        driveLink('Dossier BAC français — sujets'),
        driveLink('Dossier exercices — 3AS'),
        { label: 'Cours: Méthodologie', url: subjUrl('french', '3as'), type: 'course' },
        { label: 'BAC 2025 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bac/francais', type: 'exam' },
        { label: 'BAC 2024 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bac/francais', type: 'exam' },
        { label: 'BAC 2023 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bac/francais', type: 'exam' },
        { label: 'BAC 2022 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bac/francais', type: 'exam' },
        { label: 'BAC 2021 — Français + Corrigé', url: 'https://www.dzexams.com/fr/bac/francais', type: 'exam' },
      ],
    },
  ],
  islamic: [
    {
      level: '1AM', title: 'العقيدة والعبادات',
      links: [
        videoLink('قناة 1AM الرسمية — تربية إسلامية', levelYoutube['1AM']),
        ...(subjectYoutube.islamic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية الإسلامية — 1AM'),
        driveLink('مجلّد دروس + حلول — 1AM'),
        { label: 'درس: أركان الإسلام', url: subjUrl('islamic', '1am'), type: 'course' },
        { label: 'تمارين: الوضوء والصلاة', url: subjUrl('islamic', '1am'), type: 'td' },
        { label: 'فروض واختبارات 1AM', url: 'https://www.dzexams.com/fr/1am/tarbia-islamia', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'الهدي النبوي والأخلاق',
      links: [
        videoLink('قناة 2AM الرسمية — تربية إسلامية', levelYoutube['2AM']),
        ...(subjectYoutube.islamic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية الإسلامية — 2AM'),
        driveLink('مجلّد دروس + حلول — 2AM'),
        { label: 'درس: الحديث الشريف', url: subjUrl('islamic', '2am'), type: 'course' },
        { label: 'تمارين: الأخلاق الإسلامية', url: subjUrl('islamic', '2am'), type: 'td' },
        { label: 'فروض واختبارات 2AM', url: 'https://www.dzexams.com/fr/2am/tarbia-islamia', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'الفقه وأحكام الزكاة',
      links: [
        videoLink('قناة 3AM الرسمية — تربية إسلامية', levelYoutube['3AM']),
        ...(subjectYoutube.islamic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية الإسلامية — 3AM'),
        driveLink('مجلّد دروس + حلول — 3AM'),
        { label: 'درس: أحكام الزكاة', url: subjUrl('islamic', '3am'), type: 'course' },
        { label: 'تمارين: فقه العبادات', url: subjUrl('islamic', '3am'), type: 'td' },
        { label: 'فروض واختبارات 3AM', url: 'https://www.dzexams.com/fr/3am/tarbia-islamia', type: 'exam' },
      ],
    },
    {
      level: '4AM', title: 'القرآن والحديث — تحضير BEM',
      links: [
        videoLink('قناة 4AM — مراجعة تربية إسلامية BEM', levelYoutube['4AM']),
        ...(subjectYoutube.islamic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BEM تربية إسلامية'),
        driveLink('مجلد تمارين — 4AM'),
        { label: 'دروس 4AM تربية إسلامية', url: subjUrl('islamic', '4am'), type: 'course' },
        { label: 'تمارين شاملة', url: subjUrl('islamic', '4am'), type: 'td' },
        { label: 'فروض واختبارات 4AM', url: 'https://www.dzexams.com/fr/4am/tarbia-islamia', type: 'exam' },
        { label: 'BEM Tarbia Islamia 2025', url: 'https://www.dzexams.com/fr/bem/tarbia-islamia', type: 'exam' },
        { label: 'BEM Tarbia Islamia 2024', url: 'https://www.dzexams.com/fr/bem/tarbia-islamia', type: 'exam' },
        { label: 'BEM Tarbia Islamia 2023', url: 'https://www.dzexams.com/fr/bem/tarbia-islamia', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'مقاصد الشريعة',
      links: [
        videoLink('قناة 1AS الرسمية — تربية إسلامية', levelYoutube['1AS']),
        ...(subjectYoutube.islamic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية الإسلامية — 1AS'),
        driveLink('مجلّد دروس — 1AS'),
        { label: 'درس: مقاصد الشريعة', url: subjUrl('islamic', '1as'), type: 'course' },
        { label: 'تمارين: قواعد الفقه', url: subjUrl('islamic', '1as'), type: 'td' },
        { label: 'فروض واختبارات 1AS', url: 'https://www.dzexams.com/fr/1as/tarbia-islamia', type: 'exam' },
      ],
    },
    {
      level: '2AS', title: 'علم الكلام والفكر الإسلامي',
      links: [
        videoLink('قناة 2AS الرسمية — تربية إسلامية', levelYoutube['2AS']),
        ...(subjectYoutube.islamic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية الإسلامية — 2AS'),
        driveLink('مجلّد دروس — 2AS'),
        { label: 'درس: التوحيد والصفات', url: subjUrl('islamic', '2as'), type: 'course' },
        { label: 'تمارين: الفرق الإسلامية', url: subjUrl('islamic', '2as'), type: 'td' },
        { label: 'فروض واختبارات 2AS', url: 'https://www.dzexams.com/fr/2as/tarbia-islamia', type: 'exam' },
      ],
    },
    {
      level: '3AS', title: 'الاجتهاد والتجديد — تحضير BAC',
      links: [
        videoLink('قناة 3AS — BAC تربية إسلامية', levelYoutube['3AS']),
        ...(subjectYoutube.islamic?.map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BAC تربية إسلامية — مواضيع'),
        driveLink('مجلد تمارين — 3AS'),
        { label: 'درس: الاجتهاد الفقهي', url: subjUrl('islamic', '3as'), type: 'course' },
        { label: 'تمارين: أدلة الأحكام', url: subjUrl('islamic', '3as'), type: 'td' },
        { label: 'فروض واختبارات 3AS', url: 'https://www.dzexams.com/fr/3as/tarbia-islamia', type: 'exam' },
        { label: 'BAC Tarbia Islamia 2025', url: 'https://www.dzexams.com/fr/bac/tarbia-islamia', type: 'exam' },
        { label: 'BAC Tarbia Islamia 2024', url: 'https://www.dzexams.com/fr/bac/tarbia-islamia', type: 'exam' },
        { label: 'BAC Tarbia Islamia 2023', url: 'https://www.dzexams.com/fr/bac/tarbia-islamia', type: 'exam' },
        { label: 'BAC Tarbia Islamia 2022', url: 'https://www.dzexams.com/fr/bac/tarbia-islamia', type: 'exam' },
        { label: 'BAC Tarbia Islamia 2021', url: 'https://www.dzexams.com/fr/bac/tarbia-islamia', type: 'exam' },
      ],
    },
  ],
  civic: [
    {
      level: '1AM', title: 'الحقوق والواجبات',
      links: [
        videoLink('قناة 1AM الرسمية — تربية مدنية', levelYoutube['1AM']),
        ...(subjectYoutube.civic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية المدنية — 1AM'),
        driveLink('مجلّد دروس — 1AM'),
        { label: 'درس: حقوق الإنسان', url: subjUrl('civic', '1am'), type: 'course' },
        { label: 'تمارين: المواطنة', url: subjUrl('civic', '1am'), type: 'td' },
        { label: 'فروض واختبارات 1AM', url: 'https://www.dzexams.com/fr/1am/education-civique', type: 'exam' },
      ],
    },
    {
      level: '2AM', title: 'المؤسسات والدستور',
      links: [
        videoLink('قناة 2AM الرسمية — تربية مدنية', levelYoutube['2AM']),
        ...(subjectYoutube.civic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية المدنية — 2AM'),
        driveLink('مجلّد دروس — 2AM'),
        { label: 'درس: الدستور الجزائري', url: subjUrl('civic', '2am'), type: 'course' },
        { label: 'تمارين: مؤسسات الدولة', url: subjUrl('civic', '2am'), type: 'td' },
        { label: 'فروض واختبارات 2AM', url: 'https://www.dzexams.com/fr/2am/education-civique', type: 'exam' },
      ],
    },
    {
      level: '3AM', title: 'المشاركة المجتمعية',
      links: [
        videoLink('قناة 3AM الرسمية — تربية مدنية', levelYoutube['3AM']),
        ...(subjectYoutube.civic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية المدنية — 3AM'),
        driveLink('مجلّد دروس — 3AM'),
        { label: 'درس: الانتخابات', url: subjUrl('civic', '3am'), type: 'course' },
        { label: 'تمارين: المجتمع المدني', url: subjUrl('civic', '3am'), type: 'td' },
        { label: 'فروض واختبارات 3AM', url: 'https://www.dzexams.com/fr/3am/education-civique', type: 'exam' },
      ],
    },
    {
      level: '4AM', title: 'الهوية الوطنية — تحضير BEM',
      links: [
        videoLink('قناة 4AM — BEM تربية مدنية', levelYoutube['4AM']),
        ...(subjectYoutube.civic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BEM تربية مدنية'),
        driveLink('مجلد تمارين — 4AM'),
        { label: 'دروس 4AM تربية مدنية', url: subjUrl('civic', '4am'), type: 'course' },
        { label: 'BEM 2025 — Éducation Civique', url: 'https://www.dzexams.com/fr/bem/education-civique', type: 'exam' },
        { label: 'BEM 2024 — Éducation Civique', url: 'https://www.dzexams.com/fr/bem/education-civique', type: 'exam' },
        { label: 'BEM 2023 — Éducation Civique', url: 'https://www.dzexams.com/fr/bem/education-civique', type: 'exam' },
      ],
    },
    {
      level: '1AS', title: 'النظام السياسي الجزائري',
      links: [
        videoLink('قناة 1AS الرسمية — تربية مدنية', levelYoutube['1AS']),
        ...(subjectYoutube.civic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية المدنية — 1AS'),
        driveLink('مجلّد دروس — 1AS'),
        { label: 'درس: السلطات الثلاث', url: subjUrl('civic', '1as'), type: 'course' },
        { label: 'تمارين: الديمقراطية', url: subjUrl('civic', '1as'), type: 'td' },
      ],
    },
    {
      level: '2AS', title: 'القانون والعدالة',
      links: [
        videoLink('قناة 2AS الرسمية — تربية مدنية', levelYoutube['2AS']),
        ...(subjectYoutube.civic?.slice(0, 2).map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد تمارين التربية المدنية — 2AS'),
        driveLink('مجلّد دروس — 2AS'),
        { label: 'درس: القضاء الجزائري', url: subjUrl('civic', '2as'), type: 'course' },
        { label: 'تمارين: حقوق المتهم', url: subjUrl('civic', '2as'), type: 'td' },
      ],
    },
    {
      level: '3AS', title: 'المواطنة العالمية — BAC',
      links: [
        videoLink('قناة 3AS — BAC تربية مدنية', levelYoutube['3AS']),
        ...(subjectYoutube.civic?.map(v => videoLink(v.label, v.url)) || []),
        driveLink('مجلد BAC تربية مدنية — مواضيع'),
        driveLink('مجلد تمارين — 3AS'),
        { label: 'درس: المنظمات الدولية', url: subjUrl('civic', '3as'), type: 'course' },
        { label: 'BAC 2025 — Éducation Civique', url: 'https://www.dzexams.com/fr/bac/education-civique', type: 'exam' },
        { label: 'BAC 2024 — Éducation Civique', url: 'https://www.dzexams.com/fr/bac/education-civique', type: 'exam' },
      ],
    },
  ],
};

export const resourceData = allResourceData;

export const levelBadge: Record<string, string> = {
  '1AM': 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300',
  '2AM': 'bg-teal-100 dark:bg-teal-900/30 text-teal-700 dark:text-teal-300',
  '3AM': 'bg-cyan-100 dark:bg-cyan-900/30 text-cyan-700 dark:text-cyan-300',
  '4AM': 'bg-sky-100 dark:bg-sky-900/30 text-sky-700 dark:text-sky-300',
  '1AS': 'bg-violet-100 dark:bg-violet-900/30 text-violet-700 dark:text-violet-300',
  '2AS': 'bg-fuchsia-100 dark:bg-fuchsia-900/30 text-fuchsia-700 dark:text-fuchsia-300',
  '3AS': 'bg-pink-100 dark:bg-pink-900/30 text-pink-700 dark:text-pink-300',
};

export const linkTypes: Record<string, string> = {
  course: 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300',
  exam: 'bg-rose-100 dark:bg-rose-900/30 text-rose-700 dark:text-rose-300',
  td: 'bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300',
  tp: 'bg-cyan-100 dark:bg-cyan-900/30 text-cyan-700 dark:text-cyan-300',
  video: 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300',
  drive: 'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300',
  pdf: 'bg-slate-100 dark:bg-slate-900/30 text-slate-700 dark:text-slate-300',
};

export const linkLabels: Record<string, string> = {
  course: '📖 درس',
  exam: '📄 امتحان',
  td: '✏️ تمرين',
  tp: '🔬 TP',
  video: '🎥 فيديو',
  drive: '📁 Drive',
  pdf: '📕 PDF',
};

export const iconMap: Record<string, string> = {
  Calculator: '📐',
  Atom: '⚛️',
  FlaskConical: '🧪',
  BookOpen: '📖',
  Landmark: '🏛️',
  Dna: '🧬',
  Languages: '🗣️',
  Shield: '🛡️',
};

export const examSections = [
  { title: '📄 BEM — جميع المواد مع التصحيح', years: bemYears, url: 'https://www.dzexams.com/fr/bem', type: 'exam' },
  { title: '📄 BAC — جميع المواد مع التصحيح', years: bacYears, url: 'https://www.dzexams.com/fr/bac', type: 'exam' },
];
